language: php

php:
  - 5.3

mysql:
  database: dkan_datastore_test
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # Install drush from git clone
  - git clone --branch 6.x https://github.com/drush-ops/drush.git
  - export PATH="`pwd`/drush:$PATH"

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database dkan_datastore_test'
  - drush --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/dkan_datastore_test --enable=simpletest dkan_datastore_test

  # Grab dkan_dataset
  - git clone --branch 7.x-1.x https://github.com/nuams/dkan_dataset.git
  # copy dkan_dataset to sites/all
  - cp -r dkan_dataset dkan_datastore_test/drupal/sites/all/modules/dkan_dataset
  # copy dkan_datastore to sites/all
  - cp -r $TRAVIS_BUILD_DIR dkan_datastore_test/drupal/sites/all/modules/dkan_datastore

  # Jump into setup directory
  - cd dkan_datastore_test/drupal
  # Make dkan_dataset
  - drush make -v --no-core --yes sites/all/modules/dkan_dataset/dkan_dataset.make
  # Make dkan_datastore
  - drush make -v --no-core --yes sites/all/modules/dkan_datastore/dkan_datastore.make

  # Add patched version of feeds_flatstore_processor
  - rm -rf sites/all/modules/contrib/feeds_flatstore_processor
  - git clone https://github.com/nuams/feeds_flatstore_processor.git sites/all/modules/contrib/feeds_flatstore_processor

  # Enable modules
  - drush --yes pm-enable dkan_datastore_api

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  # Run test suite
  - drush test-run --xml 'DKAN Datastore' --uri=http://127.0.0.1:8080

notifications:
  slack:
    rooms:
      - nucivic:t3p2KxXdzymmwxitWPvfAsnK#monitor-devops
      - nucivic:t3p2KxXdzymmwxitWPvfAsnK#monitor-dkan
      - nucivic:t3p2KxXdzymmwxitWPvfAsnK#monitor-data-starter
