<?php

/**
 * @file
 * Depracated File.  Not for use, but for reference
 * Array below generated by code and likely out of date
 *
 */


$entries = array(
    'cn=hpotter,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'hpotter',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'hpotter@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '1',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '101',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Potter',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Harry',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '3.8',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=hgrainger,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'hgrainger',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'hgrainger@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '2',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '102',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Granger',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Hermione',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '4',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=rweasley,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'rweasley',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'rweasley@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '3',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '103',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Weasley',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Ron',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '3.6',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=fweasley,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'fweasley',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'fweasley@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '4',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '104',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Weasley',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Fred',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '3',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=gweasley,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'gweasley',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'gweasley@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '5',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '105',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Weasley',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'George',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '2.7',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=dmalfoy,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'dmalfoy',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'dmalfoy@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '6',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '106',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Malfoy',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Draco',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Slytherin',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '3.7',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=triddle,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'triddle',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'triddle@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '7',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '107',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Riddle',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Tom',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Slytherin',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '3.6',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=ggoyle,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'ggoyle',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'ggoyle@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '8',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '108',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Goyle',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Gregory',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Slytherin',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '3.3',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=ssnape,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'ssnape',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'ssnape@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '9',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '109',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Snape',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Severus ',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Slytherin',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => 'Defence Against the Dark Arts professor ',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 0,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=adumbledore,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'adumbledore',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'adumbledore@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '10',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '110',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Dumbledore',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Albus',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => 'Head Master Of Hogwarts',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 0,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=mmcgonagall,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'mmcgonagall',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'mmcgonagall@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '11',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '111',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'McGonagall',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Minerva',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => 'Tranfiguration/ Deputy Head Mistress',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 0,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=spomana,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'spomana',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'spomana@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '12',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '112',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Pomona',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Sprout',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Hufflepuff',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => 'Herbology',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 0,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=rhagrid,ou=people,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'rhagrid',
        'count' => 1,
      ),
      'mail' =>
      array(
        0 => 'rhagrid@hogwarts.edu',
        'count' => 1,
      ),
      'uid' =>
      array(
        0 => '13',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => '113',
        'count' => 1,
      ),
      'sn' =>
      array(
        0 => 'Hagrid',
        'count' => 1,
      ),
      'givenname' =>
      array(
        0 => 'Rubeus',
        'count' => 1,
      ),
      'house' =>
      array(
        0 => 'Gryffindor',
        'count' => 1,
      ),
      'department' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'faculty' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'staff' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'student' =>
      array(
        0 => 1,
        'count' => 1,
      ),
      'gpa' =>
      array(
        0 => '',
        'count' => 1,
      ),
      'probation' =>
      array(
        0 => 0,
        'count' => 1,
      ),
      'password' =>
      array(
        0 => 'goodpwd',
        'count' => 1,
      ),
      'count' => 14,
    ),
    'cn=gryffindor,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'gryffindor',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '1',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 201,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=hpotter,ou=people,dc=hogwarts,dc=edu',
        1 => 'cn=hgrainger,ou=people,dc=hogwarts,dc=edu',
        2 => 'cn=rweasley,ou=people,dc=hogwarts,dc=edu',
        3 => 'cn=fweasley,ou=people,dc=hogwarts,dc=edu',
        4 => 'cn=gweasley,ou=people,dc=hogwarts,dc=edu',
        5 => 'cn=mmcgonagall,ou=people,dc=hogwarts,dc=edu',
        6 => 'cn=rhagrid,ou=people,dc=hogwarts,dc=edu',
        'count' => 7,
      ),
    ),
    'cn=slytherin,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'slytherin',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '2',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 202,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=dmalfoy,ou=people,dc=hogwarts,dc=edu',
        1 => 'cn=triddle,ou=people,dc=hogwarts,dc=edu',
        2 => 'cn=ggoyle,ou=people,dc=hogwarts,dc=edu',
        3 => 'cn=ssnape,ou=people,dc=hogwarts,dc=edu',
        4 => 'cn=dmalfoy,ou=people,dc=hogwarts,dc=edu',
        'count' => 5,
      ),
    ),
    'cn=hufflepuff,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'hufflepuff',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '3',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 203,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=spomana,ou=people,dc=hogwarts,dc=edu',
        'count' => 1,
      ),
    ),
    'cn=students,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'students',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '4',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 204,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=hpotter,ou=people,dc=hogwarts,dc=edu',
        1 => 'cn=hgrainger,ou=people,dc=hogwarts,dc=edu',
        2 => 'cn=rweasley,ou=people,dc=hogwarts,dc=edu',
        3 => 'cn=fweasley,ou=people,dc=hogwarts,dc=edu',
        4 => 'cn=gweasley,ou=people,dc=hogwarts,dc=edu',
        5 => 'cn=dmalfoy,ou=people,dc=hogwarts,dc=edu',
        6 => 'cn=ggoyle,ou=people,dc=hogwarts,dc=edu',
        'count' => 7,
      ),
    ),
    'cn=honors students,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'honors students',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '5',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 205,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=hpotter,ou=people,dc=hogwarts,dc=edu',
        1 => 'cn=hgrainger,ou=people,dc=hogwarts,dc=edu',
        'count' => 2,
      ),
    ),
    'cn=probation students,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'probation students',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '6',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 206,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=dmalfoy,ou=people,dc=hogwarts,dc=edu',
        1 => 'cn=ggoyle,ou=people,dc=hogwarts,dc=edu',
        'count' => 2,
      ),
    ),
    'cn=faculty,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'faculty',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '7',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 207,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=ssnape,ou=people,dc=hogwarts,dc=edu',
        1 => 'cn=adumbledore,ou=people,dc=hogwarts,dc=edu',
        2 => 'cn=mmcgonagall,ou=people,dc=hogwarts,dc=edu',
        3 => 'cn=spomana,ou=people,dc=hogwarts,dc=edu',
        'count' => 4,
      ),
    ),
    'cn=staff,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'staff',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '8',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 208,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=rhagrid,ou=people,dc=hogwarts,dc=edu',
        'count' => 1,
      ),
    ),
    'cn=users,ou=groups,dc=hogwarts,dc=edu' =>
    array(
      'cn' =>
      array(
        0 => 'users',
        'count' => 1,
      ),
      'gid' =>
      array(
        0 => '9',
        'count' => 1,
      ),
      'guid' =>
      array(
        0 => 209,
        'count' => 1,
      ),
      'member' =>
      array(
        0 => 'cn=students,ou=groups,dc=hogwarts,dc=edu',
        1 => 'cn=faculty,ou=groups,dc=hogwarts,dc=edu',
        2 => 'cn=staff,ou=groups,dc=hogwarts,dc=edu',
        'count' => 3,
      ),
    ),
  );
