<?php
/**
 * @file
 * Code for the CU Twitter Feed feature.
 */

include_once 'cu_twitter_feed.features.inc';

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got node--person.tpl.php in our module directory.
 */
function cu_twitter_feed_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_twitter_feed');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
	  if (isset($theme_registry[$h]['theme paths'])) {
	    $first_element = array_shift($theme_registry[$h]['theme paths']);
	    array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
  	}
  }
}

function cu_twitter_feed_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'cu_twitter_feed'). '/cu_twitter_feed.css');
}