<?php
/**
 * @file
 * cu_twitter_feed.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function cu_twitter_feed_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'bean-twitter_block-field_twitter_block_items'.
  $field_instances['bean-twitter_block-field_twitter_block_items'] = array(
    'bundle' => 'twitter_block',
    'default_value' => array(
      0 => array(
        'value' => 4,
      ),
    ),
    'deleted' => 0,
    'description' => 'Leave blank to embed recent timeline.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'number',
        'settings' => array(),
        'type' => 'number_unformatted',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'bean',
    'fences_wrapper' => 'no_wrapper',
    'field_name' => 'field_twitter_block_items',
    'label' => 'Number of Tweets',
    'required' => 0,
    'settings' => array(
      'max' => 100,
      'min' => 1,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'bean-twitter_block-field_twitter_block_user'.
  $field_instances['bean-twitter_block-field_twitter_block_user'] = array(
    'bundle' => 'twitter_block',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'fences_wrapper' => 'no_wrapper',
    'field_name' => 'field_twitter_block_user',
    'label' => 'Twitter User Name',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'bean-twitter_block-field_twitter_style'.
  $field_instances['bean-twitter_block-field_twitter_style'] = array(
    'bundle' => 'twitter_block',
    'default_value' => array(
      0 => array(
        'value' => 'white',
      ),
    ),
    'default_value_function' => '',
    'default_value_php' => '',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_key',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'bean',
    'fences_wrapper' => 'div',
    'field_name' => 'field_twitter_style',
    'label' => 'Style',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Leave blank to embed recent timeline.');
  t('Number of Tweets');
  t('Style');
  t('Twitter User Name');

  return $field_instances;
}
