; This file was auto-generated by drush make
core = 7.x
api = 2

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[express][download][type] = ""
projects[express][download][url] = ""
projects[express][type] = "module"

projects[views_bulk_operations][version] = "3.1"

projects[administerusersbyrole][version] = "1.0-beta1"

projects[attachment_links][version] = "1.0+6-dev"

projects[auto_entitylabel][version] = "1.2"

projects[bean][version] = "1.7"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[block_styles][download][type] = ""
projects[block_styles][download][url] = ""
projects[block_styles][type] = "module"
projects[block_styles][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[block_title_icons][download][type] = ""
projects[block_title_icons][download][url] = ""
projects[block_title_icons][type] = "module"
projects[block_title_icons][version] = "1.0"

projects[blocktheme][version] = "1.1"

projects[ctools][version] = "1.7"

projects[ckeditor_link][version] = "2.3"

projects[colorbox][version] = "2.4"

projects[comment_notify][subdir] = "contrib"
projects[comment_notify][version] = "1.2"

projects[context][version] = "3.6"

projects[context_query_param][subdir] = "contrib"
projects[context_query_param][version] = "1.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_article][download][type] = ""
projects[cu_article][download][url] = ""
projects[cu_article][type] = "module"
projects[cu_article][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_block][download][type] = ""
projects[cu_block][download][url] = ""
projects[cu_block][type] = "module"
projects[cu_block][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_block_selector][download][type] = ""
projects[cu_block_selector][download][url] = ""
projects[cu_block_selector][type] = "module"
projects[cu_block_selector][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_events_calendar_block][download][type] = ""
projects[cu_events_calendar_block][download][url] = ""
projects[cu_events_calendar_block][type] = "module"
projects[cu_events_calendar_block][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_hero_unit][download][type] = ""
projects[cu_hero_unit][download][url] = ""
projects[cu_hero_unit][type] = "module"
projects[cu_hero_unit][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_image_styles][download][type] = ""
projects[cu_image_styles][download][url] = ""
projects[cu_image_styles][type] = "module"
projects[cu_image_styles][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_video][download][type] = ""
projects[cu_video][download][url] = ""
projects[cu_video][type] = "module"
projects[cu_video][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cu_wysiwyg][download][type] = ""
projects[cu_wysiwyg][download][url] = ""
projects[cu_wysiwyg][type] = "module"
projects[cu_wysiwyg][version] = "1.0"

projects[date][version] = "2.8"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[ds][version] = "2.6"

projects[email][version] = "1.2"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[eva][version] = "1.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features][download][type] = ""
projects[features][download][url] = ""
projects[features][type] = "module"

projects[fences][version] = "1.0"

projects[field_collection][version] = "1.0-beta5"

projects[field_group][version] = "1.3"

projects[media][version] = "1.4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[files][download][type] = ""
projects[files][download][url] = ""
projects[files][type] = "module"
projects[files][version] = "1.0"

projects[fitvids][version] = "1.14"

projects[flexslider][version] = "2.0-alpha3"

projects[flexslider_views_slideshow][version] = "2.x-dev"

projects[globalredirect][version] = "1.5"

projects[google_appliance][version] = "1.11"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[grid_size_blocks][download][type] = ""
projects[grid_size_blocks][download][url] = ""
projects[grid_size_blocks][type] = "module"
projects[grid_size_blocks][version] = "1.0"

projects[image_url_formatter][version] = "1.4"

projects[inline_entity_form][version] = "1.5"

projects[jquery_update][version] = "2.3"

projects[ldap][version] = "1.0-beta12"

projects[libraries][version] = "2.2"

projects[link][version] = "1.1"

projects[menu_block][version] = "2.5"

projects[migrate][version] = "2.5"

projects[module_filter][version] = "2.0-alpha2"

projects[navigation404][version] = "1.0"

projects[patch_manager][subdir] = "contrib"
projects[patch_manager][version] = "1.0"

projects[pathauto][version] = "1.2"

projects[pathologic][version] = "2.12"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[people_content_type][download][type] = ""
projects[people_content_type][download][url] = ""
projects[people_content_type][type] = "module"
projects[people_content_type][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[photo_gallery][download][type] = ""
projects[photo_gallery][download][url] = ""
projects[photo_gallery][type] = "module"
projects[photo_gallery][version] = "1.0"

projects[quicktabs][version] = "3.6"

projects[role_delegation][version] = "1.1"

projects[secure_permissions][version] = "1.6"

projects[securepages][version] = "1.0-beta2"

projects[shortcode][version] = "2.0"

projects[smart_trim][version] = "1.4"

projects[smartcrop][version] = "1.0-beta2+1-dev"

projects[strongarm][version] = "2.0"

projects[taxonomy_formatter][version] = "1.4"

projects[token][version] = "1.5"

projects[typogrify][version] = "1.0-rc8"

projects[video_embed_field][version] = "2.0-beta5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.10"

projects[views_accordion][version] = "1.0-rc2"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "4.5"

projects[wysiwyg][version] = "2.2+23-dev"

projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[omega][version] = "3.1"

projects[rubik][version] = "4.0-beta8"

projects[tao][version] = "3.0-beta4"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cores][download][type] = ""
projects[cores][download][url] = ""
projects[cores][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[custom][download][type] = ""
projects[custom][download][url] = ""
projects[custom][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[themes][download][type] = ""
projects[themes][download][url] = ""
projects[themes][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = ""
libraries[flexslider][download][url] = ""
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imgareaselect][download][type] = ""
libraries[jquery.imgareaselect][download][url] = ""
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backstretch][download][type] = ""
libraries[backstretch][download][url] = ""
libraries[backstretch][directory_name] = "backstretch"
libraries[backstretch][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tablesorter][download][type] = ""
libraries[tablesorter][download][url] = ""
libraries[tablesorter][directory_name] = "tablesorter"
libraries[tablesorter][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fitvids][download][type] = ""
libraries[fitvids][download][url] = ""
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[custom][download][type] = ""
libraries[custom][download][url] = ""
libraries[custom][directory_name] = "custom"
libraries[custom][type] = "library"
