<?php
/**
 * @file
 * Code for the CU Block Layout feature.
 */

/**
 * Implements hook_entity_info().
 */
function cu_class_entity_info() {
  $info = array();

  $info['cu_class'] = array(
    'label' => t('Class'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'cu_class',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'class_id',
      'title' => 'title',
      'bundle' => 'type',
    ),
    'module' => 'cu_class',
    // Attach bundles - i.e. alternative configurations of fields associated with a main entity.
    'bundles' => array(
      'class' => array(
        'label' => 'Class',
         // Information below is used by the Field UI - they "attach" themselves here and lets us
         // do the standard field management that all the core entities enjoy.
         'admin' => array(
           'path' => 'admin/structure/class/manage',
            'access arguments' => array('administer class content'),
          ),
        ),
      ),
      'uri callback' => 'entity_class_uri',
      'load hook' => 'cu_class_load',
      'view modes' => array(
        'full' => array(
          'label' => t('Default'),
          'custom settings' => FALSE,
        ),
        'short' => array(
          'label' => t('Short'),
          'custom settings' => FALSE,
        ),
        'list' => array(
          'label' => t('List'),
          'custom settings' => FALSE,
        ),
      ),
  );

  return $info;
}
/**
 * Implements hook_entity_info_alter().
 */
function cu_class_entity_info_alter(&$entity_info) {

}

/**
 * Implements hook_flush_caches().
 */
function cu_class_flush_caches() {
  return array('cache_class');
}

/**
 * Implements hook_ctools_plugin_api().
 */
function cu_class_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implements hook_views_api().
 */
function cu_class_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}


/**
 * Implements hook_menu().
 */
function cu_class_menu() {
  // Add Class
  $items['class/add'] = array(
    'title' => 'Add Class',
    'page callback' => 'cu_class_add',
    'access callback' => array('administer class content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $class_uri = 'class/%cu_class';
  $class_uri_argument_position = 1;

  $items[$class_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('cu_class', $class_uri_argument_position),
    'page callback' => 'cu_class_view',
    'page arguments' => array($class_uri_argument_position),
    'access arguments' => array($class_uri_argument_position),
    'access callback' => 'cu_class_access',
    'file' => 'cu_class.pages.inc',
  );

  $items[$class_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$class_uri . '/delete'] = array(
    'title' => 'Delete',
    'title callback' => 'cu_class_label',
    'title arguments' => array($class_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_class_delete_form', $class_uri_argument_position),
    'access arguments' => array('administer class content'),
    'file' => 'cu_class.admin.inc',
  );

  $items[$class_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_class_form', $class_uri_argument_position),
    'access arguments' => array('administer class content'),
    'file' => 'cu_class.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

   // This provides a place for Field API to hang its own
  // interface and has to be the same as what was defined
  // in class_entity_info() above.
  $items['admin/structure/class/manage'] = array(
    'title' => 'Class',
    'description' => 'Manage Class Entity Structure',
    'page callback' => 'cu_class_admin_page',
    'access arguments' => array('administer class content'),
    'weight' => -50,
  );

  // Class related settings users can access
  $items['admin/settings/classes'] = array(
    'title' => 'Classes',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer express settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'weight' => -20,
  );

  $items['admin/settings/classes/class-bulk-unpublish'] = array(
    'title' => 'Bulk Unpublish Classes',
    'description' => 'Entering a list of classes will unpubish them',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_class_bulk_unpublish_form'),
    'access arguments' => array('administer class content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Access callback for ???
 */
function cu_class_access($class) {

  if ($class->status < 1 && !user_access('view unpublished classes')) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Implements hook_permission().
 */
function cu_class_permission() {
  return array(
    'administer class content' => array(
      'title' => 'Administer Class Content',
      'description' => 'Full access to classes',
    ),
    'import classes' => array(
      'title' => 'Import Class Content',
      'description' => 'Allows user to find a specific class or group of classes to import',
    ),
    'override class fields' => array(
      'title' => 'Override Class Fields',
      'description' => 'Modify fields added to Class entity',
    ),
    'view unpublished classes' => array(
      'title' => 'View Unpublished Class Content',
      'description' => '',
    ),
  );
}



/**
 * Implements hook_entity_view().
 */
function cu_class_entity_view($entity, $type, $view_mode) {
  if ($type == 'cu_class') {
    // alter it here
    //dsm($entity);
    //view unpublished classes
  }
}


/**
 * Creates an class entity for us - simply intializing the main variables and
 * sending us to a form to add in the rest.
 */
function cu_class_add() {

  $class = entity_create('cu_class', array('type' => 'class'));

  return drupal_get_form('cu_class_form', $class);
}

/**
 * Class Form.
 */
function cu_class_form($form, &$form_state, $class) {

  $form_state['class'] = $class;

  field_attach_form('cu_class', $class, $form, $form_state);

  $submit = array();
  if (!empty($form['#submit'])) {
    $submit += $form['#submit'];
  }

  $form['actions'] = array(
    '#weight' => 100,
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save class'),
    '#submit' => $submit + array('cu_class_form_submit'),
  );

  $form['additional_settings'] = array(
      '#type' => 'vertical_tabs',
      '#weight' => 99,
  );

  // Create a fieldset that will be included in the vertical tab.
  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Publishing options'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    // Send this tab to the top of the list.
    '#weight' => -99,
    // The #group value must match the name of the vertical tabs element.
    // In most cases, this is 'additional_settings'.
    '#group' => 'additional_settings',
    '#attributes' => array('class' => array('node-form-options')),
  );

  $form['options']['status'] = array(
    '#type' => 'checkbox',
    '#title' => t('Published'),
    '#default_value' => $class->status,
  );

  return $form;
}

/**
 * Class submit handler.
 */
function cu_class_form_submit($form, &$form_state) {

  $class = $form_state['class'];

  entity_form_submit_build_entity('cu_class', $class, $form, $form_state);

  $class->status = $class->options['status'];

  entity_save('cu_class', $class);

  //$class_uri = entity_uri('cu_class', $class);
  //$form_state['redirect'] = $class_uri['path'];

  $form_state['redirect'] = 'class/' . $class->class_id;

  drupal_set_message(t('Class %title saved.', array('%title' => entity_label('cu_class', $class))));
}

/**
 * Class Bulk Unpublish Form.
 */
function cu_class_bulk_unpublish_form($form, &$form_state) {

  $form['cu_class_bulk_unpublish_class_ids'] = array(
    '#type' => 'textarea',
    '#default_value' => variable_get('cu_class_bulk_unpublish_class_ids', ''),
    '#title' => t('Class IDs to Unpublish'),
    '#description' => t('Comma seperated list of class ids to unpublish'),
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Unpublish'),
  );

  return $form;
}

/**
 * Process form
 */
function cu_class_bulk_unpublish_form_submit($form, &$form_state) {
  //remove spaces
  $cu_class_bulk_unpublish_class_ids = str_replace(" ", "", $form['cu_class_bulk_unpublish_class_ids']['#value']);
  variable_set('cu_class_bulk_unpublish_class_ids', $cu_class_bulk_unpublish_class_ids);
  $classes = explode(",", $form['cu_class_bulk_unpublish_class_ids']['#value']);

  foreach ($classes as $class_id) {
    $class = entity_load_single('cu_class', $class_id);
    if ($class) {
      $class->status = -2;
      $updated = entity_save('cu_class', $class);
      drupal_set_message('Unpublished ' . $class->field_class_subject[LANGUAGE_NONE][0]['value'] . " " . $class->field_class_catalog_nbr[LANGUAGE_NONE][0]['value'] . " - " . $class->title , 'status');
    } else {
      drupal_set_message('Class number  ' . $class_id . ' was not found and could not be unpublished', 'warning');
    }
  }

}

/**
 * Just provide some airing info for the entity administration page.
 * This can be expanded to add more information / a list of all created entites, etc.
 */
function cu_class_admin_page() {
  //$output = 'Welcome to the administration page for your Airing Entities.<br/>';
  //$output .= '<ul class="action-links"><li><a href="/airing/add">Add Airing</a></li></ul>';
  //return $output;

  // Not sure why we'd need an admin landing page, so I'm redirecting to field

  drupal_goto('admin/structure/class/manage/fields');
}

/**
 * Load a class.
 */
function cu_class_load($class_id, $reset = FALSE) {
  $classes = cu_class_load_multiple(array($class_id), array(), $reset);
  //dsm($classes);
  return reset($classes);
}

/**
 * Load multiple classes based on certain conditions.
 */
function cu_class_load_multiple($class_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('cu_class', $class_ids, $conditions, $reset);
}

/**
 * Implements hook_theme_registry_alter().
 */
function cu_class_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_class');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'cu_class', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('cu_class');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}

function cu_class_preprocess_entity(&$vars) {
  $entity_type = $vars['elements']['#entity_type'];
  $bundle = $vars['elements']['#bundle'];
  if (($entity_type == 'cu_class') && ($bundle == 'class')) {
    if ($vars['view_mode'] == 'short') {
      $vars['theme_hook_suggestions'][] = 'cu_class__short';
    }
    if ($vars['view_mode'] == 'list') {
      $vars['theme_hook_suggestions'][] = 'cu_class__list';
    }
    $title = array();
    $title[] = $vars['content']['field_class_subject'][0]['#markup'];
    $title[] = $vars['content']['field_class_catalog_nbr'][0]['#markup'];
    $title[] = '<span class="class-title">' . $vars['content']['field_class_course_title_long'][0]['#markup'] . '</span>';

    $course_link_title = $vars['content']['field_class_course_title_long'][0]['#markup'] . ' - Section ' .  $vars['content']['field_class_class_section'][0]['#markup'];
    $vars['course_link'] = l($course_link_title, 'course/' . $vars['content']['field_class_crse_id'][0]['#markup'], array('query' => array('class_id' => $vars['content']['field_class_class_nbr'][0]['#markup'])));

    // Dates
    $vars['start_date'] = cu_class_date_format(strtotime($vars['content']['field_class_start_dt']['#items'][0]['value']));
    $vars['end_date'] = cu_class_date_format(strtotime($vars['content']['field_class_end_dt']['#items'][0]['value']));
    $vars['updated'] = 'Updated: ' . format_date(strtotime($vars['content']['field_class_last_updated']['#items'][0]['value']), 'cu_short_date_time');

    // Available seats
    $cap = intval($vars['content']['field_class_enrl_cap'][0]['#markup']);
    $total = intval($vars['content']['field_class_enrl_tot'][0]['#markup']);
    $available = $cap - $total;
    if ($available == 1) {
      $vars['available'] = $available . ' seat available';
    } else {
      $vars['available'] = $available . ' seats available';
    }
    if (isset($vars['content']['field_class_crse_attr']) && $vars['content']['field_class_crse_attr'][0]['#markup'] == 'BCRQ') {
      $reqs = $vars['content']['field_class_crse_attr_value'][0]['#markup'];
      $vars['course_requirements'] = cu_class_core_requirements($reqs);
    }
    else {
      $vars['course_requirements'] = '';
    }
    $format = $vars['content']['field_class_instruction_mode_des'][0]['#markup'];
    $format_parts = explode('/', $format);
    foreach ($format_parts as $key => $part) {
      $format_parts[$key] = '<span>' . $part . '</span>';
    }
    $format = join(' / ', $format_parts);
    $vars['format'] = $format;

    $session = $vars['content']['field_class_session_code'][0]['#markup'];
    $vars['session'] = cu_class_session_translator($session);

    // Meeting time
    $meeting_time_raw = $vars['content']['field_class_ssr_mtg_sched_long'][0]['#markup'];
    $meeting_time_exempt = array (
      'tba',
      'TBA',
      'tbd',
      'TBD',
    );
    if (!in_array($meeting_time_raw, $meeting_time_exempt)) {
      $meeting_time_parts = explode(' ', $meeting_time_raw);
      // Meeting schedule display
      foreach ($meeting_time_parts as $key => $part) {
        // Add spaces to days
        if (ctype_alpha($part)) {
          $regex = '/(?<!^)((?<![[:upper:]])[[:upper:]]|[[:upper:]](?![[:upper:]]))/';
          $meeting_time_parts[$key] = preg_replace( $regex, ' $1', $part ) . '<br />';
        }
        // Convert to 12hour time
        if (strpos($part, ':') !== FALSE) {
          $meeting_time_parts[$key] = date('g:i a', strtotime($part));
        }
      }
      $vars['meeting_time'] = join(' ',$meeting_time_parts);
    }
    else {
      $vars['meeting_time'] = $meeting_time_raw;
    }
  }
}

function cu_class_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'cu_class') . '/css/cu-class.css');
}

function cu_class_core_requirements($reqs) {
  $keys = explode(', ', $reqs);
  $keys = array_unique($keys, SORT_REGULAR);
  $requirements = array(
    'AD' => 'Human Diversity',
    'AF' => 'Foreign Language',
    'AH' => 'Historical Context',
    'AI' => 'Ideals & Values',
    'AL' => 'Literature and the Arts',
    'AQ' => 'Quantitative Reasoning & Mathmatical Skills',
    'AS' => 'Contemporary Societies',
    'AU' => 'United States Context',
    'AW' => 'Written Communication',
    'AX' => 'Natural Sciences Sequence',
    'AY' => 'Natural Sciences Non-sequence',
    'AZ' => 'Natural Sciences Lab',
  );
  $values = array();
  foreach ($keys as $key) {
    if (isset($requirements[$key])) {
      $values[] = $requirements[$key];
    }
  }
  return join(', ', $values);
}

function cu_class_core_requirements_values() {
  $requirements = array(
    'AD' => 'Human Diversity',
    'AF' => 'Foreign Language',
    'AH' => 'Historical Context',
    'AI' => 'Ideals & Values',
    'AL' => 'Literature and the Arts',
    'AQ' => 'Quantitative Reasoning & Mathmatical Skills',
    'AS' => 'Contemporary Societies',
    'AU' => 'United States Context',
    'AW' => 'Written Communication',
    'AX' => 'Natural Sciences Sequence',
    'AY' => 'Natural Sciences Non-sequence',
    'AZ' => 'Natural Sciences Lab',
  );
  // Cache available class formats
  if ($cache = cache_get('cu_class_search_requirements_available')) {
    $requirements = $cache->data;
  } else {
    $query = db_select('field_data_field_class_crse_attr_value', 'req');
    $query->fields('req', array('field_class_crse_attr_value_value'));
    $query->groupBy('req.field_class_crse_attr_value_value');
    $class_reqs = $query->execute()->fetchCol();
    $current_reqs = array();
    foreach ($class_reqs as $class_req) {
      if (strpos($class_req, ', ') !== FALSE) {
        $keys = explode(', ', $class_req);
        foreach($keys as $key) {
          $current_reqs[$key] = $key;
        }
      }
      else {
        $current_reqs[$class_req] = $class_req;
      }
    }
    foreach ($requirements as $key => $requirement) {
      if (!array_key_exists($key, $current_reqs)) {
        unset($requirements[$key]);
      }
    }
    asort($requirements);
    cache_set('cu_class_search_requirements_available', $requirements, 'cache', time() + 60 * 60 * 24);
  }
  return $requirements;
}

function cu_class_subject_translate($subject) {
  $subjects = array(
    'AREN' => 'Architecture Engineering',
    'GEOG' => 'Geography',
    'PHIL' => 'Philosophy',
    'HIST' => 'History',
    'JRNL' => 'Journalism',
    'IAFS' => 'International Affairs',
    'HUMN' => 'Humanities',
    'ENGL' => 'English',
    'ECON' => 'Economics',
    'JPNS' => 'Japanese ',
    'ANTH' => 'Anthropology',
    'LEAD' => 'Leadership',
    'ETHN' => 'Ethnic Studies',
    'MUEL' => 'Music',
    'EDUC' => 'Education',
    'LAWS' => 'Law',
    'CLAS' => 'Classics',
    'DNCE' => 'Dance',
    'THTR' => 'Theater',
    'ATOC' => 'Atmospheric & Oceanic Sciences',
    'PSYC' => 'Psychology & Neuroscience',
    'FREN' => 'French',
    'RUSS' => 'Russian',
    'EBIO' => 'Ecology & Evolutionary Biology',
    'PHYS' => 'Physics',
    'MCEN' => 'Mechanical Engineering',
    'CVEN' => 'Civil Engineering',
    'ENVD' => 'Environmental Design',
    'CSCI' => 'Computer Sciences',
    'SPAN' => 'Spanish',
    'ACCT' => 'Accounting',
    'ANTH' => 'Anthropology',
    'APPM' => 'Applied Mathematics',
    'APRD' => 'Advertising, Public Relations and Media Design',
    'AREN' => 'Architecture Engineering',
    'ARTF' => 'Art & Art History-Film',
    'ARTH' => 'Art History',
    'ARTS' => 'Art-Studio',
    'ASEN' => 'Aerospace Engineering Sciences',
    'ASIA' => 'Asian Studies',
    'ASTR' => 'Astrophysical & Planetary Sciences',
    'ATLS' => 'ATLAS',
    'ATOC' => 'Atmospheric & Oceanic Sciences',
    'BADM' => 'Business Administration',
    'BCOR' => 'Business Core',
    'BPOL' => 'Business Policy & Strategic Management',
    'CESR' => 'Current Emphasis on Social Responsibility',
    'CHEM' => 'Chemistry & Biochemistry',
    'CHEN' => 'Chemical Engineering',
    'CLAS' => 'Classics',
    'CMDP' => 'Critical Media Practices',
    'COEN' => 'Engineering & Applied Science Administration',
    'COML' => 'Comparative Literature',
    'COMM' => 'Communications',
    'CSCI' => 'Computer Science, Engineering & Applied Science',
    'CVEN' => 'Civil, Environmental & Architectural Engineering',
    'DNCE' => 'Dance',
    'EBIO' => 'Ecology & Evolutionary Biology',
    'ECEN' => 'Electrical, Computer & Energy Engineering',
    'ECON' => 'Economics',
    'EDUC' => 'Education',
    'EMEN' => 'Engineering Management',
    'ENGL' => 'English',
    'ENVD' => 'Environmental Design',
    'ENVS' => 'Environmental Studies',
    'ESBM' => 'Entrepreneurship & Small Business',
    'ETHN' => 'Ethnic Studies',
    'FILM' => 'Film Studies',
    'FNCE' => 'Finance',
    'FREN' => 'French',
    'GEEN' => 'General Engineering',
    'GEOG' => 'Geography',
    'GEOL' => 'Geological Sciences',
    'GRMN' => 'Germanic & Slavic Language & Literature',
    'HIST' => 'History',
    'HIND' => 'Hindi',
    'HONR' => 'Honors',
    'HUEN' => 'Humanities for Engineers',
    'HUMN' => 'Humanities',
    'IAFS' => 'International Affairs',
    'INBU' => 'International Business',
    'IPHY' => 'Integrative Physiology',
    'ITAL' => 'Italian',
    'JPNS' => 'Japanese',
    'JRNL' => 'Journalism',
    'JWST' => 'Jewish Studies',
    'KREN' => 'Korean',
    'LATN' => 'Latin',
    'LAWS' => 'Law',
    'LDSP' => 'Leadership Residential Academic Program',
    'LEAD' => 'CU Engage',
    'LING' => 'Linguistics',
    'MATH' => 'Mathematics',
    'MCDB' => 'Molecular and Cellular and Developmental Biology ',
    'MCEN' => 'Mechanical Engineering',
    'MDST' => 'Media Studies',
    'MGMT' => 'Management',
    'MKTG' => 'Marketing',
    'MSBX' => 'Business Elective',
    'MSBC' => 'Business Core',
    'MUEL' => 'Music',
    'MUSC' => 'Music',
    'MUSM' => 'Museum Studies',
    'NRSC' => 'Psychology & Neuroscience',
    'PHIL' => 'Philosophy',
    'PHYS' => 'Physics',
    'PRLC' => 'Presidents Leadership Class, Cross College Program',
    'PSCI' => 'Political Science',
    'PSYC' => 'Psychology',
    'REAL' => 'Real Estate',
    'RLST' => 'Religious Studies',
    'RUSS' => 'Russian',
    'SCAN' => 'Nordic',
    'SLHS' => 'Speech, Language and Hearing Sciences',
    'SOCY' => 'Sociology',
    'SPAN' => 'Spanish',
    'THTR' => 'Theater',
    'TLEN' => 'Telecommunication',
    'TMUS' => 'Thesis Music',
    'WMST' => 'Womens Studies',
    'WRTG' => 'Writing & Rhetoric',
  );
  return $subjects[$subject];
}

function cu_class_subject_values() {
  $subjects = array(
    'AREN' => 'Architecture Engineering',
    'GEOG' => 'Geography',
    'PHIL' => 'Philosophy',
    'HIST' => 'History',
    'JRNL' => 'Journalism',
    'IAFS' => 'International Affairs',
    'HUMN' => 'Humanities',
    'ENGL' => 'English',
    'ECON' => 'Economics',
    'JPNS' => 'Japanese ',
    'ANTH' => 'Anthropology',
    'LEAD' => 'Leadership',
    'ETHN' => 'Ethnic Studies',
    'MUEL' => 'Music',
    'EDUC' => 'Education',
    'LAWS' => 'Law',
    'CLAS' => 'Classics',
    'DNCE' => 'Dance',
    'THTR' => 'Theater',
    'ATOC' => 'Atmospheric & Oceanic Sciences',
    'PSYC' => 'Psychology & Neuroscience',
    'FREN' => 'French',
    'RUSS' => 'Russian',
    'EBIO' => 'Ecology & Evolutionary Biology',
    'PHYS' => 'Physics',
    'MCEN' => 'Mechanical Engineering',
    'CVEN' => 'Civil Engineering',
    'ENVD' => 'Environmental Design',
    'CSCI' => 'Computer Sciences',
    'SPAN' => 'Spanish',
    'ACCT' => 'Accounting',
    'ANTH' => 'Anthropology',
    'APPM' => 'Applied Mathematics',
    'APRD' => 'Advertising, Public Relations and Media Design',
    'AREN' => 'Architecture Engineering',
    'ARTF' => 'Art & Art History-Film',
    'ARTH' => 'Art History',
    'ARTS' => 'Art-Studio',
    'ASEN' => 'Aerospace Engineering Sciences',
    'ASIA' => 'Asian Studies',
    'ASTR' => 'Astrophysical & Planetary Sciences',
    'ATLS' => 'ATLAS',
    'ATOC' => 'Atmospheric & Oceanic Sciences',
    'BADM' => 'Business Administration',
    'BCOR' => 'Business Core',
    'BPOL' => 'Business Policy & Strategic Management',
    'CESR' => 'Current Emphasis on Social Responsibility',
    'CHEM' => 'Chemistry & Biochemistry',
    'CHEN' => 'Chemical Engineering',
    'CLAS' => 'Classics',
    'CMDP' => 'Critical Media Practices',
    'COEN' => 'Engineering & Applied Science Administration',
    'COML' => 'Comparative Literature',
    'COMM' => 'Communications',
    'CSCI' => 'Computer Science, Engineering & Applied Science',
    'CVEN' => 'Civil, Environmental & Architectural Engineering',
    'DNCE' => 'Dance',
    'EBIO' => 'Ecology & Evolutionary Biology',
    'ECEN' => 'Electrical, Computer & Energy Engineering',
    'ECON' => 'Economics',
    'EDUC' => 'Education',
    'EMEN' => 'Engineering Management',
    'ENGL' => 'English',
    'ENVD' => 'Environmental Design',
    'ENVS' => 'Environmental Studies',
    'ESBM' => 'Entrepreneurship & Small Business',
    'ETHN' => 'Ethnic Studies',
    'FILM' => 'Film Studies',
    'FNCE' => 'Finance',
    'FREN' => 'French',
    'GEEN' => 'General Engineering',
    'GEOG' => 'Geography',
    'GEOL' => 'Geological Sciences',
    'GRMN' => 'Germanic & Slavic Language & Literature',
    'HIND' => 'Hindi',
    'HIST' => 'History',
    'HONR' => 'Honors',
    'HUEN' => 'Humanities for Engineers',
    'HUMN' => 'Humanities',
    'IAFS' => 'International Affairs',
    'INBU' => 'International Business',
    'IPHY' => 'Integrative Physiology',
    'ITAL' => 'Italian',
    'JPNS' => 'Japanese',
    'JRNL' => 'Journalism',
    'JWST' => 'Jewish Studies',
    'KREN' => 'Korean',
    'LATN' => 'Latin',
    'LAWS' => 'Law',
    'LDSP' => 'Leadership Residential Academic Program',
    'LEAD' => 'CU Engage',
    'LING' => 'Linguistics',
    'MATH' => 'Mathematics',
    'MCDB' => 'Molecular and Cellular and Developmental Biology ',
    'MCEN' => 'Mechanical Engineering',
    'MDST' => 'Media Studies',
    'MGMT' => 'Management',
    'MKTG' => 'Marketing',
    'MSBX' => 'Business Elective',
    'MSBC' => 'Business Core',
    'MUEL' => 'Music',
    'MUSC' => 'Music',
    'MUSM' => 'Museum Studies',
    'NRSC' => 'Psychology & Neuroscience',
    'PHIL' => 'Philosophy',
    'PHYS' => 'Physics',
    'PRLC' => 'Presidents Leadership Class, Cross College Program',
    'PSCI' => 'Political Science',
    'PSYC' => 'Psychology',
    'REAL' => 'Real Estate',
    'RLST' => 'Religious Studies',
    'RUSS' => 'Russian',
    'SCAN' => 'Nordic',
    'SLHS' => 'Speech, Language and Hearing Sciences',
    'SOCY' => 'Sociology',
    'SPAN' => 'Spanish',
    'THTR' => 'Theater',
    'TLEN' => 'Telecommunication',
    'TMUS' => 'Thesis Music',
    'WMST' => 'Womens Studies',
    'WRTG' => 'Writing & Rhetoric',
  );

  // Get class subjects from LOV service.
  if ($cache = cache_get('cu_class_import_subjects_display:B-CUBLD')) {
    $subjects = $cache->data;
  }
  else {
    $subjects = cu_class_import_get_colleges($institution = 'B-CUBLD', $options = array('return_subjects_display' => TRUE));
  }

  // Cache available class subjects
  if ($cache = cache_get('cu_class_search_subjects_available')) {
    $subjects = $cache->data;
  } else {
    $query = db_select('field_data_field_class_subject', 'subject');
    $query->fields('subject', array('field_class_subject_value'));
    $query->groupBy('subject.field_class_subject_value');
    $class_subjects = $query->execute()->fetchCol();

    $current_subjects = array();
    foreach ($class_subjects as $class_subject) {
      $current_subjects[$class_subject] = $class_subject;
    }
    foreach ($subjects as $key => $subject) {
      if (!array_key_exists($key, $current_subjects)) {
        unset($subjects[$key]);
      }
    }
    asort($subjects);
    cache_set('cu_class_search_subjects_available', $subjects, 'cache', time() + 60 * 60 * 24);
  }

  return $subjects;
}

function cu_class_format_translate($format) {
  $formats = cu_class_format_values();
  if (isset($formats[$format])) {
    return $formats[$format];
  }
}

function cu_class_format_values() {
  $formats = array(
    'HY' => 'Hybrid',
    'OL' => 'Online',
    'OS' => 'Online, self-paced',
    'OT' => 'Online, term-based',
    'P' => 'On Campus',

  );

  // Cache available class formats
  if ($cache = cache_get('cu_class_search_formats_available')) {
    $formats = $cache->data;
  } else {
    $query = db_select('field_data_field_class_instruction_mode', 'mode');
    $query->fields('mode', array('field_class_instruction_mode_value'));
    $query->groupBy('mode.field_class_instruction_mode_value');
    $modes = $query->execute()->fetchCol();

    $current_modes = array();
    foreach ($modes as $mode) {
      $current_modes[$mode] = $mode;
    }
    foreach ($formats as $key => $format) {
      if (!array_key_exists($key, $current_modes)) {
        unset($formats[$key]);
      }
    }
    asort($formats);
    cache_set('cu_class_search_formats_available', $formats, 'cache', time() + 60 * 60 * 24);
  }

  return $formats;
}

function cu_class_session_translator($session) {
  $sessions = array(
    'BAM'	=> 'Maymester',
    'BAS'	=> 'Session A',
    'BBS'	=> 'Session B',
    'BCS'	=> 'Session C',
    'BD1'	=> 'Session D',
    'BES'	=> 'Session E',
    'BFS'	=> 'Session F',
    'BGS'	=> 'Augmester',
  );
  if (isset($sessions[$session])) {
    return $sessions[$session];
  }
}

function cu_class_session_values() {
  $sessions = array(
    'BAM'	=> 'Maymester',
    'BAS'	=> 'Session A',
    'BBS'	=> 'Session B',
    'BCS'	=> 'Session C',
    'BD1'	=> 'Session D',
    'BES'	=> 'Session E',
    'BFS'	=> 'Session F',
    'BGS'	=> 'Augmester',
  );

  // Cache available class sessions
  if ($cache = cache_get('cu_class_search_sessions_available')) {
    $sessions = $cache->data;
  } else {
    $query = db_select('field_data_field_class_session_code', 'session');
    $query->fields('session', array('field_class_session_code_value'));
    $query->groupBy('session.field_class_session_code_value');
    $class_sessions = $query->execute()->fetchCol();

    $current_sessions = array();
    foreach ($class_sessions as $class_session) {
      $current_sessions[$class_session] = $class_session;
    }
    foreach ($sessions as $key => $session) {
      if (!array_key_exists($key, $current_sessions)) {
        unset($sessions[$key]);
      }
    }
    //asort($sessions);
    cache_set('cu_class_search_sessions_available', $sessions, 'cache', time() + 60 * 60 * 24);
  }

  return $sessions;
}

function cu_class_date_format($date) {
  // to deal with 12/31/1969 being saved when the import process has no date
  if ($date == -61200) {
    return NULL;
  }
  $date_month = date('F', $date);
  $date_day_year = date('j, Y', $date);

  if($date_month == "September"){
      $ap_date_sept = "Sept. " . $date_day_year;
      $formatted_date = $ap_date_sept;
  } elseif (strlen($date_month) > 5){
      $ap_date_short = substr($date_month, 0,3) . "." . " " . $date_day_year;
      $formatted_date = $ap_date_short;
  } else {
      $ap_date_long = $date_month . " " . $date_day_year;
      $formatted_date = $ap_date_long;
  }
  return $formatted_date;
}
