<?php
/**
 * @file
 * openpublish_related_content.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function openpublish_related_content_field_default_fields() {
  $fields = array();

  // Exported field: 'node-openpublish_article-field_op_related_nref'.
  $fields['node-openpublish_article-field_op_related_nref'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_op_related_nref',
      'foreign keys' => array(
        'nid' => array(
          'columns' => array(
            'nid' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'nid' => array(
          0 => 'nid',
        ),
      ),
      'locked' => '0',
      'module' => 'node_reference',
      'settings' => array(
        'referenceable_types' => array(
          'openpublish_article' => 'openpublish_article',
          'openpublish_blog_post' => 'openpublish_blog_post',
          'openpublish_photo_gallery' => 'openpublish_photo_gallery',
          'openpublish_site_page' => 0,
          'openpublish_video' => 'openpublish_video',
          'profile' => 0,
          'section_front' => 0,
        ),
        'view' => array(
          'args' => array(),
          'display_name' => '',
          'view_name' => '',
        ),
      ),
      'translatable' => '0',
      'type' => 'node_reference',
    ),
    'field_instance' => array(
      'bundle' => 'openpublish_article',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Article.',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '5',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '3',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_op_related_nref',
      'label' => 'Related Content',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'node_reference',
        'settings' => array(
          'autocomplete_match' => 'contains',
          'autocomplete_path' => 'node_reference/autocomplete',
          'references_dialog_add' => 1,
          'references_dialog_edit' => 1,
          'references_dialog_search' => 0,
          'references_dialog_search_view' => '',
          'size' => '60',
        ),
        'type' => 'node_reference_autocomplete',
        'weight' => '6',
      ),
    ),
  );

  // Exported field: 'node-openpublish_blog_post-field_op_related_nref'.
  $fields['node-openpublish_blog_post-field_op_related_nref'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_op_related_nref',
      'foreign keys' => array(
        'nid' => array(
          'columns' => array(
            'nid' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'nid' => array(
          0 => 'nid',
        ),
      ),
      'locked' => '0',
      'module' => 'node_reference',
      'settings' => array(
        'referenceable_types' => array(
          'openpublish_article' => 'openpublish_article',
          'openpublish_blog_post' => 'openpublish_blog_post',
          'openpublish_photo_gallery' => 'openpublish_photo_gallery',
          'openpublish_site_page' => 0,
          'openpublish_video' => 'openpublish_video',
          'profile' => 0,
          'section_front' => 0,
        ),
        'view' => array(
          'args' => array(),
          'display_name' => '',
          'view_name' => '',
        ),
      ),
      'translatable' => '0',
      'type' => 'node_reference',
    ),
    'field_instance' => array(
      'bundle' => 'openpublish_blog_post',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Blog Post.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '6',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '3',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_op_related_nref',
      'label' => 'Related Content',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'node_reference',
        'settings' => array(
          'autocomplete_match' => 'contains',
          'autocomplete_path' => 'node_reference/autocomplete',
          'references_dialog_add' => 1,
          'references_dialog_edit' => 1,
          'references_dialog_search' => 0,
          'references_dialog_search_view' => '',
          'size' => '60',
        ),
        'type' => 'node_reference_autocomplete',
        'weight' => '5',
      ),
    ),
  );

  // Exported field: 'node-openpublish_photo_gallery-field_op_related_nref'.
  $fields['node-openpublish_photo_gallery-field_op_related_nref'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_op_related_nref',
      'foreign keys' => array(
        'nid' => array(
          'columns' => array(
            'nid' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'nid' => array(
          0 => 'nid',
        ),
      ),
      'locked' => '0',
      'module' => 'node_reference',
      'settings' => array(
        'referenceable_types' => array(
          'openpublish_article' => 'openpublish_article',
          'openpublish_blog_post' => 'openpublish_blog_post',
          'openpublish_photo_gallery' => 'openpublish_photo_gallery',
          'openpublish_site_page' => 0,
          'openpublish_video' => 'openpublish_video',
          'profile' => 0,
          'section_front' => 0,
        ),
        'view' => array(
          'args' => array(),
          'display_name' => '',
          'view_name' => '',
        ),
      ),
      'translatable' => '0',
      'type' => 'node_reference',
    ),
    'field_instance' => array(
      'bundle' => 'openpublish_photo_gallery',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Photo Gallery.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '5',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '5',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_op_related_nref',
      'label' => 'Related Content',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'node_reference',
        'settings' => array(
          'autocomplete_match' => 'contains',
          'autocomplete_path' => 'node_reference/autocomplete',
          'references_dialog_add' => 1,
          'references_dialog_edit' => 1,
          'references_dialog_search' => 0,
          'references_dialog_search_view' => '',
          'size' => '60',
        ),
        'type' => 'node_reference_autocomplete',
        'weight' => '6',
      ),
    ),
  );

  // Exported field: 'node-openpublish_video-field_op_related_nref'.
  $fields['node-openpublish_video-field_op_related_nref'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_op_related_nref',
      'foreign keys' => array(
        'nid' => array(
          'columns' => array(
            'nid' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'nid' => array(
          0 => 'nid',
        ),
      ),
      'locked' => '0',
      'module' => 'node_reference',
      'settings' => array(
        'referenceable_types' => array(
          'openpublish_article' => 'openpublish_article',
          'openpublish_blog_post' => 'openpublish_blog_post',
          'openpublish_photo_gallery' => 'openpublish_photo_gallery',
          'openpublish_site_page' => 0,
          'openpublish_video' => 'openpublish_video',
          'profile' => 0,
          'section_front' => 0,
        ),
        'view' => array(
          'args' => array(),
          'display_name' => '',
          'view_name' => '',
        ),
      ),
      'translatable' => '0',
      'type' => 'node_reference',
    ),
    'field_instance' => array(
      'bundle' => 'openpublish_video',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Video.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '4',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '2',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_op_related_nref',
      'label' => 'Related Content',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'node_reference',
        'settings' => array(
          'autocomplete_match' => 'contains',
          'autocomplete_path' => 'node_reference/autocomplete',
          'references_dialog_add' => 1,
          'references_dialog_edit' => 1,
          'references_dialog_search' => 0,
          'references_dialog_search_view' => '',
          'size' => '60',
        ),
        'type' => 'node_reference_autocomplete',
        'weight' => '6',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Article.');
  t('Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Blog Post.');
  t('Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Photo Gallery.');
  t('Enter the title(s) of other Articles, Blog Posts, Galleries, or Videos that you wish to explicitly relate to this Video.');
  t('Related Content');

  return $fields;
}
