<?php
/**
 * Preprocess html.
 */
function cu_livechat_preprocess_html(&$vars) {
  // Get livechat ID and build javascript
  if ($livechat_license = variable_get('livechat_license_number', NULL)) {
    $livechat = "var __lc = {}; __lc.license = " . $livechat_license . ";
    (function() {
      var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
      lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
    })();";

    if (!path_is_admin(current_path())) {
      drupal_add_js($livechat, 'inline');
    }

    // Keep livechat from displaying when printing.
    drupal_add_css(
      '#livechat-compact-container { display: none !important;}',
      array(
        'group' => CSS_THEME,
        'type' => 'inline',
        'media' => 'print',
        'preprocess' => FALSE,
        'weight' => '9999',
      )
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * LiveChat config onto Settings form.
 */
function cu_livechat_form_cu_settings_admin_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['livechat'] = array(
    '#type' => 'fieldset',
    '#title' => t('Live Chat'),
    '#description' => 'A paid real-time chat solution from LiveChat (<a href="http://www.livechatinc.com/">http://www.livechatinc.com/</a>). The department or academic unit will need to purchase a license in order to use this service. A free trial is available.',
  );
  $form['livechat']['livechat_license_number'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('livechat_license_number', NULL),
    '#required' => FALSE,
    '#title' => 'LiveChatINC.com license number',
    '#description' => '<em>Example: 1234567</em>',
  );
  $form['#validate'][] = '_cu_livechat_config_form_validate';
}

/**
 * Validation handler for _cu_livechat_config_form.
 */
function _cu_livechat_config_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['livechat_license_number']) && !empty($form_state['values']['livechat_license_number'])) {
    $error = t('The livechat license number must only contain numbers.');
    form_set_error('livechat_license_number', $error);
  }
}

