<?php
/**
 * Implements hook_install().
 */
function cu_test_content_blocks_install() {
  module_load_include('module', 'bean');
  _cu_test_content_blocks_events();
  _cu_test_content_blocks_twitter();
  _cu_test_content_blocks_text();
  _cu_test_content_blocks_text_map();
  _cu_test_content_blocks_article_list();
  _cu_test_content_blocks_article_grid();
  _cu_test_content_blocks_hero();
  _cu_test_content_blocks_social();
  _cu_test_content_blocks_content_grid();
  _cu_test_content_blocks_blocktheme();
  _cu_test_content_blocks_icons();
  _cu_test_content_articles_create_blocks_node();
}

/**
 * Install events calendar block.
 */
function _cu_test_content_blocks_events() {

  $temp_beans = variable_get('cu_test_content_beans', array());

  $values = array(
    'delta' => 'events_list_block',
    'label' => 'events_list_block',
    'title' => 'Upcoming Events',
    'type' => 'cu_events_calendar_block',
    'view_mode' => 'default',
  );

  $values['field_event_categories'][LANGUAGE_NONE][0]['value'] = '30-0';
  $values['field_event_expire'][LANGUAGE_NONE][0]['value'] = 'yes';
  $values['field_event_link'][LANGUAGE_NONE][0]['url'] = 'http://events.colorado.edu';
  $values['field_event_link'][LANGUAGE_NONE][0]['title'] = 'View all events';
  $values['field_event_number'][LANGUAGE_NONE][0]['value'] = '5';
  $values['field_event_subcategories'][LANGUAGE_NONE][0]['value'] = 'N';
  $values['field_event_template'][LANGUAGE_NONE][0]['value'] = '44';
  $values['field_event_type'][LANGUAGE_NONE][0]['value'] = 'N';

  $bean = bean_create($values);
  $bean->save();

  $title = $values['title'] . '|' . $values['label'];
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);
  return $bean;
}

/**
 * Install Twitter block.
 */
function _cu_test_content_blocks_twitter() {

  $temp_beans = variable_get('cu_test_content_beans', array());

  $values = array(
    'delta' => 'twitter_block',
    'label' => 'twitter_block',
    'title' => 'Follow us on Twitter',
    'type' => 'twitter_block',
    'view_mode' => 'default',
  );
  $values['field_twitter_block_user'][LANGUAGE_NONE][0]['value'] = 'cuboulder';
  $bean = bean_create($values);
  $bean->save();

  $title = $values['title'] . '|' . $values['label'];
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);
  return $bean;
}
/**
 * Install Text blocks.
 */
function _cu_test_content_blocks_text() {

  $temp_beans = variable_get('cu_test_content_beans', array());

  $titles = array(
    'text_block_one' => 'Text Block One',
    'text_block_two' => 'Text Block Two',
    'text_block_three' => 'Text Block Three',
    'text_block_four' => 'Text Block Four',
    'text_block_five' => 'Text Block Five',
    'text_block_six' => 'Text Block Six',
    'text_block_seven' => 'Text Block Seven',
    'text_block_eight' => 'Text Block Eight',
    'text_block_nine' => 'Text Block Nine',
    'text_block_ten' => 'Text Block Ten',
    'text_block_eleven' => 'Text Block Eleven',
    'text_block_twelve' => 'Text Block Twelve',
  );
  foreach ($titles as $label => $title) {
    $values = array(
      'delta' => $label,
      'label' => $label,
      'title' => $title,
      'type' => 'block',
      'view_mode' => 'default',
    );

    $values['field_block_text'][LANGUAGE_NONE][0]['value'] = _cu_test_content_blocks_dummy_text();
    $values['field_block_text'][LANGUAGE_NONE][0]['format'] = 'wysiwyg';
    $bean = bean_create($values);
    $bean->save();

    $title = $values['title'] . '|' . $values['label'];
    $temp_beans[$bean->bid] = $title;
    drupal_set_message("Bean $title - $bean->bid created");
    variable_set('cu_test_content_beans', $temp_beans);
  }
}

/**
 * Install Text Map block.
 */
function _cu_test_content_blocks_text_map() {

  $temp_beans = variable_get('cu_test_content_beans', array());


  $values = array(
    'delta' => 'map',
    'label' => 'map',
    'title' => 'Visit Us',
    'type' => 'block',
    'view_mode' => 'default',
  );

  $values['field_block_text'][LANGUAGE_NONE][0]['value'] = '[map]https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d764.0113974567611!2d-105.26909819309007!3d40.007429217600766!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x80fe73b4583c4777!2sColorado+University+Art+Museum!5e0!3m2!1sen!2sus!4v1415306653827[/map]';
  $values['field_block_text'][LANGUAGE_NONE][0]['format'] = 'wysiwyg';
  $bean = bean_create($values);
  $bean->save();

  $title = $values['title'] . '|' . $values['label'];
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);

}

/**
 * Install Article list block.
 */
function _cu_test_content_blocks_article_list() {

  $temp_beans = variable_get('cu_test_content_beans', array());

  $values = array(
    'delta' => 'article_list_block',
    'label' => 'article_list_block',
    'title' => 'News & Announcements',
    'type' => 'articles',
    'view_mode' => 'default',
  );
  $values['field_article_items_display'][LANGUAGE_NONE][0]['value'] = 3;
  $values['field_article_link'][LANGUAGE_NONE][0]['title'] = 'More news';
  $values['field_article_link'][LANGUAGE_NONE][0]['url'] = 'news-announcements';

  $bean = bean_create($values);
  $bean->save();

  $title = $values['title'] . '|' . $values['label'];
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);
}

/**
 * Install Article grid block.
 */
function _cu_test_content_blocks_article_grid() {

  $temp_beans = variable_get('cu_test_content_beans', array());

  $values = array(
    'delta' => 'article_grid_block',
    'label' => 'article_grid_block',
    'title' => 'Latest News & Announcements',
    'type' => 'article_grid',
    'view_mode' => 'default',
  );
  $values['field_article_grid_items'][LANGUAGE_NONE][0]['value'] = 3;
  $values['field_article_grid_summary'][LANGUAGE_NONE][0]['value'] = 'summary-hide';

  $bean = bean_create($values);
  $bean->save();

  $title = $values['title'] . '|' . $values['label'];
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);
}

/**
 * Install Hero Unit block.
 */
function _cu_test_content_blocks_hero() {
  $temp_beans = variable_get('cu_test_content_beans', array());

  $values = array(
    'delta' => 'hero_unit',
    'label' => 'hero_unit',
    'title' => '',
    'type' => 'hero_unit',
    'view_mode' => 'default',
  );

  $values['field_hero_unit_headline'][LANGUAGE_NONE][0]['value'] = 'This is a hero unit';
  $values['field_hero_unit_text'][LANGUAGE_NONE][0]['value'] = _cu_test_content_blocks_dummy_text_hero();
  $values['field_hero_unit_text'][LANGUAGE_NONE][0]['format'] = 'plain';
  $values['field_hero_unit_link'][LANGUAGE_NONE][0]['title'] = 'Learn More';
  $values['field_hero_unit_link'][LANGUAGE_NONE][0]['url'] = 'http://www.colorado.edu';
  $values['field_hero_unit_text_color'][LANGUAGE_NONE][0]['value'] = 'white';
  $values['field_hero_unit_link_color'][LANGUAGE_NONE][0]['value'] = 'outline-white';
  $values['field_hero_unit_bg_color'][LANGUAGE_NONE][0]['value'] = 'black';
  $values['field_hero_unit_text_align'][LANGUAGE_NONE][0]['value'] = 'left-half';

  $file_path = system_retrieve_file('https://unsplash.it/1500/1000?random');
    $file = (object) array(
      'uid' => $count,
      'uri' => $file_path,
      'filemime' => file_get_mimetype($file_path),
      'status' => 1,
    );
    // You can specify a subdirectory, e.g. public://foo/
    $file = file_copy($file, 'public://');
    $values['field_hero_unit_image'][LANGUAGE_NONE][0] = (array) $file;

  $bean = bean_create($values);
  $bean->save();

  $title = $values['title'] . '|' . $values['label'];
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);
}

function _cu_test_content_blocks_social() {
  $temp_beans = variable_get('cu_test_content_beans', array());


  $bean = bean_create(array('type' => 'social_links'));
  $bean->label = 'social_links';
  $bean->title = 'Connect with Us';
  $bean->delta = 'social_links';

  _cu_test_content_create_social_field_collection_item($bean, 'facebook', 'http://facebook.com',1);
  _cu_test_content_create_social_field_collection_item($bean, 'twitter', 'http://twitter.com',2);
  _cu_test_content_create_social_field_collection_item($bean, 'youtube', 'http://youtube.com',3);
  _cu_test_content_create_social_field_collection_item($bean, 'linkedin', 'http://linkedin.com',4);
  _cu_test_content_create_social_field_collection_item($bean, 'instagram', 'http://instagram.com',5);

  $bean->save();

  $title = $bean->title . '|' . $bean->label;
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);

}
function _cu_test_content_create_social_field_collection_item($bean, $type, $url, $order) {
  $fc_item = entity_create('field_collection_item', array('field_name' => 'field_social_links_collection'));
  $fc_item->setHostEntity('bean', $bean);

  $fc_item->field_social_link_type[LANGUAGE_NONE][$order]['value'] = $type;
  $fc_item->field_social_link_url[LANGUAGE_NONE][$order]['url'] = $url;

  $fc_item->save();
  return TRUE;
}

function _cu_test_content_blocks_content_grid() {
  $temp_beans = variable_get('cu_test_content_beans', array());


  $bean = bean_create(array('type' => 'feature_callout'));
  $bean->label = 'content_grid';
  $bean->title = '';
  $bean->delta = 'content_grid';
  $bean->field_callout_columns[LANGUAGE_NONE][0]['value'] = 3;

  $title_salt = _cu_test_content_grid_titles_dummy_text();
  $titles = explode('.', $title_salt);

  _cu_test_content_create_grid_field_collection_item($bean, $titles[0], 'grid1.jpg' ,1);
  _cu_test_content_create_grid_field_collection_item($bean, $titles[1], 'grid2.jpg' ,2);
  _cu_test_content_create_grid_field_collection_item($bean, $titles[2], 'grid3.jpg' ,3);


  $bean->save();

  $title = $bean->title . '|' . $bean->label;
  $temp_beans[$bean->bid] = $title;
  drupal_set_message("Bean $title - $bean->bid created");
  variable_set('cu_test_content_beans', $temp_beans);
}

function _cu_test_content_create_grid_field_collection_item($bean, $title, $image, $order) {
  $fc_item = entity_create('field_collection_item', array('field_name' => 'field_callouts'));
  $fc_item->setHostEntity('bean', $bean);
  $text = _cu_test_content_grid_dummy_text();
  $fc_item->field_callout_title[LANGUAGE_NONE][$order]['title'] = $title;
  $fc_item->field_callout_text[LANGUAGE_NONE][$order]['value'] = $text;
  $fc_item->field_callout_text[LANGUAGE_NONE][$order]['format'] = 'wysiwyg';

  $file_path = system_retrieve_file('https://unsplash.it/1500/1000?random');
  $file = (object) array(
    'uid' => 1,
    'uri' => $file_path,
    'filemime' => file_get_mimetype($file_path),
    'status' => 1,
  );
  // You can specify a subdirectory, e.g. public://foo/
  $file = file_copy($file, 'public://');
  $fc_item->field_callout_image[LANGUAGE_NONE][$count] = (array) $file;
  $fc_item->field_callout_image[LANGUAGE_NONE][$count]['alt'] = 'Photo Alt Text';

  $fc_item->save();
  return TRUE;
}




/**
 * Block Dummy text.
 */
function _cu_test_content_blocks_dummy_text() {
  $response = drupal_http_request('http://loripsum.net/api/1/short/link');
  if ($response->code == '200') {
    return $response->data;
  } else {
    return 'No dummy text.';
  }
}

/**
 * Hero Dummy text.
 */
function _cu_test_content_blocks_dummy_text_hero() {
  $response = drupal_http_request('http://loripsum.net/api/1/short/plaintext');
  if ($response->code == '200') {
    return $response->data;
  } else {
    return 'No dummy text.';
  }
}

/**
 * Grid Dummy text.
 */
function _cu_test_content_grid_dummy_text() {
  $response = drupal_http_request('http://loripsum.net/api/1/medium');
  if ($response->code == '200') {
    return $response->data;
  } else {
    return 'No dummy text.';
  }
}
/**
 * Grid Titles Dummy text.
 */
function _cu_test_content_grid_titles_dummy_text() {
  $response = drupal_http_request('http://loripsum.net/api/1/long/plaintext');
  if ($response->code == '200') {
    return $response->data;
  } else {
    return 'No dummy text.';
  }
}


function _cu_test_content_blocks_blocktheme() {
  $block_theme = array(
    'bean-text_block_eleven' => 'blockoutline',
    'bean-text_block_twelve' => 'blockdarkgray',
  );
  variable_set('blocktheme', $block_theme);
}
function _cu_test_content_blocks_icons() {
  $icons = array(
    'bean-events_list_block' => 'fa-calendar',
    'bean-text_block_eleven' => 'fa-globe',
    'bean-text_block_twelve' => 'fa-university',
  );
  variable_set('block_title_icons', $icons);
}

function _cu_test_content_articles_create_blocks_node() {
  $nodes = array(
    '1' => array(
      'title' => 'Blocks',
      'link_title' => 'Blocks',
    ),
  );
  foreach ($nodes as $elem) {
    $node_title = $elem['title'];
    $node = new StdClass();
    $node->title = $node_title;
    $node->language = LANGUAGE_NONE;
    $node->body[$node->language][0]['format']  = 'wysiwyg';
    $node->type = 'page';
    $node->menu = array(
      'menu_name' => 'main-menu',
      'plid' => $plid,
      'link_title' => $elem['link_title'],
      'enabled' => TRUE,
      'weight' => 99,
    );
    $node->uid = 1;
    node_save($node);
    variable_set('cu_test_content_blocks_page', $node->nid);
  }
}


/**
 * Implements hook_uninstall.
 */

function cu_test_content_blocks_uninstall() {
  $temp_beans = variable_get('cu_test_content_beans', NULL);
  if ($temp_beans) {
    foreach ($temp_beans as $bid => $name) {
      $bean = bean_load($bid);
      bean_delete($bean);
      drupal_set_message("Bean $name - $bid deleted.");
    }
    variable_del('cu_test_content_beans');
  }
  $temp_block_page = variable_get('cu_test_content_blocks_page', NULL);
  if ($temp_block_page) {
    node_delete($temp_block_page);
    drupal_set_message("Node $temp_block_page deleted.");
    variable_del('cu_test_content_blocks_page');
  }
}
