<?php
/**
 * @file
 * cu_content_list.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cu_content_list_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_content_list_display'.
  $field_bases['field_content_list_display'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_content_list_display',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(),
      'allowed_values_function' => 'cu_content_list_display_values',
      'allowed_values_php' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_content_list_reference'.
  $field_bases['field_content_list_reference'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_content_list_reference',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'article' => 'article',
          'collection_item' => 'collection_item',
          'issue' => 'issue',
          'page' => 'page',
          'person' => 'person',
          'photo_gallery' => 'photo_gallery',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_content_list_sort'.
  $field_bases['field_content_list_sort'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_content_list_sort',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'custom_order' => 'Custom Order',
        'date_created' => 'Date Created',
        'date_created_reverse' => 'Date Created Reverse',
        'alpha' => 'Alphabetical',
      ),
      'allowed_values_function' => 'cu_content_list_sort_values',
      'allowed_values_php' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
