language: node_js
node_js:
  - 0.6
  - 0.8
  - '0.10'
  - 0.11
  - 0.12
before_install:
  - "test $TRAVIS_NODE_VERSION = '0.6' && npm install -g npm@1.3.26 || npm install -g npm"
matrix:
  allow_failures:
    - node_js: 0.11