<?php
/**
 * @file
 * Code for the CU Webform feature.
 */

include_once 'cu_webform.features.inc';

/**
 * Implements hook_menu().
 */
function cu_webform_menu() {
  $items = array();
  $items['admin/content/webform/add'] = array(
    'title' => 'Add Webform',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/webform'),
    'access callback' => '_node_add_access',
    //'access arguments' => array('create webform content'),
    'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}

/**
 *  Implements hook_form_FORM_ID_alter.
 */
function cu_webform_form_webform_node_form_alter(&$form, &$form_state, $form_id) {
  // Only do this for new nodes
  if ($form['nid']['#value'] == NULL) {
    $form['menu']['enabled']['#default_value'] = TRUE;
  }
}

/**
 * Implements hook_menu_alter.
 * Alter titles of webform links
 */
function cu_webform_menu_alter(&$items) {
  //while these end up being node/% in the menu router table
  //they are declared as node/%webform_menu in Webform's hook_menu.
  // Using node/% alters the access, but don't understand why
  $items['node/%webform_menu/webform']['title'] = 'Edit Webform';
  $items['node/%webform_menu/webform-results']['title'] = 'Webform Results';
}
