language: node_js
node_js:
  - 0.10.28
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install -g bower
  - bower install
script:
  - node_modules/karma/bin/karma start --single-run --browsers PhantomJS