language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
    - node_js: "0.12"
    - node_js: "iojs"
install:
  - npm install -g gulp
  - npm install bower -g
  - npm run setup
script:
  - gulp css
  - gulp js
  - gulp images
  - gulp fonts
  - gulp scss-lint
  - gulp js-lint
