<?php

/**
 * @file
 * Contains Drupal hooks for the Tracking Pixels module.
 */

/**
 * Implements hook_embed_templates_types().
 *
 * @return array
 *   List of custom embed types.
 */
function et_tracking_pixels_embed_templates_types() {
  // Create a few initial embed types.
  $custom_types = array();
  $module_path = drupal_get_path('module', 'et_tracking_pixels');
  $default_status = 'unpublished';

  $custom_types['facebook'] = array(
    'label' => 'Facebook',
    'form_callback' => 'et_tp_facebook_form',
    'submission_callback' => NULL,
    'renderer' => 'page_top_bottom',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/embed-templates-facebook',
  );

  $custom_types['doubleclick'] = array(
    'label' => 'Doubleclick',
    'form_callback' => 'et_tp_doubleclick_form',
    'submission_callback' => NULL,
    'renderer' => 'page_top_bottom',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/embed-templates-doubleclick',
  );

  $custom_types['twitter'] = array(
    'label' => 'Twitter',
    'form_callback' => 'et_tp_twitter_form',
    'submission_callback' => NULL,
    'renderer' => 'page_top_bottom',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/embed-templates-twitter',
  );

  return $custom_types;
}

/**
 * Creates a form element for position that all tracking pixels can use.
 *
 * @param array $data
 *   Unserialized data from the existing embed.
 *
 * @return array
 *   Form element.
 */
function et_tp_get_position_element($data = array()) {
  $position_options = array(
    'top' => 'Top',
    'bottom' => 'Bottom',
  );
  return array(
    '#title' => t('Position'),
    '#type' => 'select',
    '#options' => $position_options,
    '#description' => t('Choose where on the page the embed is placed. Look at the embed code instructions to determine where it should be placed.'),
    '#default_value' => !empty($data['position']) ? $data['position'] : 0,
  );
}

/**
 * Form values for Facebook tracking pixel.
 *
 * @param array $form
 *   Form containing default embed template form options.
 * @param array $form_state
 *   State of the default embed template form.
 * @param int|null $id
 *   ID of the current embed being edited if that embed exists.
 * @param array $data
 *   Data of the current embed if it is being edited.
 */
function et_tp_facebook_form(&$form, &$form_state, $id = NULL, $data = array()) {

  $size = variable_get('et_form_field_size', 128);

  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Embed Data'),
    '#weight' => -10,
  );

  $form['options']['account_id'] = array(
    '#title' => t('ID'),
    '#description' => t('The ID of tracking pixel.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['account_id']) ? $data['account_id'] : '',
    '#required' => TRUE,
    '#size' => $size,
  );

  $form['options']['action'] = array(
    '#title' => t('Action'),
    '#description' => t('An optional activity being tracked. "Pageview" is already added to the code.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['action']) ? $data['action'] : '',
    '#size' => $size,
  );

  $form['options']['position'] = et_tp_get_position_element($data);
}

/**
 * Form values for Facebook tracking pixel.
 *
 * @param array $form
 *   Form containing default embed template form options.
 * @param array $form_state
 *   State of the default embed template form.
 * @param int|null $id
 *   ID of the current embed being edited if that embed exists.
 * @param array $data
 *   Data of the current embed if it is being edited.
 */
function et_tp_doubleclick_form(&$form, &$form_state, $id = NULL, $data = array()) {

  $size = variable_get('et_form_field_size', 128);

  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Embed Data'),
    '#weight' => -10,
  );

  $form['options']['account_id'] = array(
    '#title' => t('ID'),
    '#description' => t('Your Campaign ID.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['account_id']) ? $data['account_id'] : '',
    '#required' => TRUE,
    '#size' => $size,
  );

  $form['options']['activity'] = array(
    '#title' => t('Activity'),
    '#description' => t('Activity name of this tag.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['activity']) ? $data['activity'] : '',
    '#size' => $size,
  );

  $form['options']['creation'] = array(
    '#title' => t('Creation Date'),
    '#description' => t('Creation date of this campaign.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['creation']) ? $data['creation'] : '',
    '#size' => $size,
  );

  $form['options']['page_location'] = array(
    '#title' => t('Page Location'),
    '#description' => t('URL where tracking pixel will be added.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['page_location']) ? $data['page_location'] : '',
    '#size' => $size,
  );

  $form['options']['type'] = array(
    '#title' => t('Type'),
    '#description' => t('Type of campaign.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['type']) ? $data['type'] : '',
    '#size' => $size,
  );

  $form['options']['category'] = array(
    '#title' => t('Category'),
    '#description' => t('Category of campaign.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['category']) ? $data['category'] : '',
    '#size' => $size,
  );

  $form['options']['position'] = et_tp_get_position_element($data);
}

/**
 * Form values for Facebook tracking pixel.
 *
 * @param array $form
 *   Form containing default embed template form options.
 * @param array $form_state
 *   State of the default embed template form.
 * @param int|null $id
 *   ID of the current embed being edited if that embed exists.
 * @param array $data
 *   Data of the current embed if it is being edited.
 */
function et_tp_twitter_form(&$form, &$form_state, $id = NULL, $data = array()) {

  $size = variable_get('et_form_field_size', 128);

  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Embed Data'),
    '#weight' => -10,
  );

  $form['options']['account_id'] = array(
    '#title' => t('ID'),
    '#description' => t('Your Campaign ID.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['account_id']) ? $data['account_id'] : '',
    '#required' => TRUE,
    '#size' => $size,
  );

  $form['options']['activity'] = array(
    '#title' => t('Activity'),
    '#description' => t('Activity name of this tag.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['action']) ? $data['action'] : '',
    '#size' => $size,
  );

  $form['options']['position'] = et_tp_get_position_element($data);
}
